esphome:
  name: bedroom-bed-controller
  friendly_name: Bedroom Bed Controller

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# ---------- WEB ----------
web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_password

# ---------- CORE ----------
logger:

api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Bed Controller Fallback"
    password: "password"

captive_portal:

# ---------- Relay ----------
output:
  - platform: gpio
    pin: 13
    id: head_up_relay

  - platform: gpio
    pin: 12
    id: head_down_relay

  - platform: gpio
    pin: 14
    id: legs_up_relay

  - platform: gpio
    pin: 27
    id: legs_down_relay

# ---------- Preset relay ----------
switch:
  - platform: gpio
    pin: 26
    id: preset_1
    restore_mode: ALWAYS_OFF
    internal: true
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: preset_1

  - platform: gpio
    pin: 25
    id: preset_2
    restore_mode: ALWAYS_OFF
    internal: true
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: preset_2

  - platform: gpio
    pin: 33
    id: level_all
    restore_mode: ALWAYS_OFF
    internal: true
    on_turn_on:
      - delay: 3s
      - switch.turn_off: level_all

# ---------- Buttons ----------
button:
  - platform: template
    name: "Preset 1"
    id: preset_1_button
    on_press:
      - cover.stop: head_cover
      - cover.stop: legs_cover
      - switch.turn_on: preset_1

  - platform: template
    name: "Preset 2"
    id: preset_2_button
    on_press:
      - cover.stop: head_cover
      - cover.stop: legs_cover
      - switch.turn_on: preset_2

  - platform: template
    name: "Flat"
    id: flat_button
    on_press:
      - cover.stop: head_cover
      - cover.stop: legs_cover
      - switch.turn_on: level_all
      # Обнуляем память штор
      - lambda: |-
          id(head_cover).position = 0.0f;
          id(legs_cover).position = 0.0f;

# ---------- Time set ----------
number:
  - platform: template
    name: "Head Duration"
    id: head_duration
    unit_of_measurement: s
    min_value: 5
    max_value: 60
    step: 1
    mode: box
    initial_value: 25
    restore_value: true
    optimistic: true
    set_action:
      - lambda: |-
          id(head_cover).set_open_duration(x * 1000);
          id(head_cover).set_close_duration(x * 1000);

  - platform: template
    name: "Legs Duration"
    id: legs_duration
    unit_of_measurement: s
    min_value: 5
    max_value: 60
    step: 1
    mode: box
    initial_value: 19
    restore_value: true
    optimistic: true
    set_action:
      - lambda: |-
          id(legs_cover).set_open_duration(x * 1000);
          id(legs_cover).set_close_duration(x * 1000);

# ---------- COVER ----------
cover:
  - platform: time_based
    name: "Head Position"
    id: head_cover
    assumed_state: true
    open_duration: 25s
    close_duration: 25s
    open_action:
      - cover.stop: legs_cover
      - output.turn_on: head_up_relay
      - output.turn_off: head_down_relay
    close_action:
      - cover.stop: legs_cover
      - output.turn_on: head_down_relay
      - output.turn_off: head_up_relay
    stop_action:
      - output.turn_off: head_up_relay
      - output.turn_off: head_down_relay

  - platform: time_based
    name: "Legs Position"
    id: legs_cover
    assumed_state: true
    open_duration: 19s
    close_duration: 19s
    open_action:
      - cover.stop: head_cover
      - output.turn_on: legs_up_relay
      - output.turn_off: legs_down_relay
    close_action:
      - cover.stop: head_cover
      - output.turn_on: legs_down_relay
      - output.turn_off: legs_up_relay
    stop_action:
      - output.turn_off: legs_up_relay
      - output.turn_off: legs_down_relay

# ---------- SELECT ----------
select:
  - platform: template
    name: "Bed Mode"
    id: bed_mode_select
    optimistic: true
    options:
      - "---"
      - Flat
      - Preset 1
      - Preset 2
    initial_option: "---"
    set_action:
      - if:
          condition:
            lambda: 'return x == "---";'
          then:
            - logger.log: "Reset selector"
          else:
            - cover.stop: head_cover
            - cover.stop: legs_cover
            - if:
                condition:
                  lambda: 'return x == "Flat";'
                then:
                  - button.press: flat_button
            - if:
                condition:
                  lambda: 'return x == "Preset 1";'
                then:
                  - button.press: preset_1_button
            - if:
                condition:
                  lambda: 'return x == "Preset 2";'
                then:
                  - button.press: preset_2_button
            - delay: 500ms
            - select.set:
                id: bed_mode_select
                option: "---"

# ---------- System ----------
sensor:
  - platform: internal_temperature
    name: "ESP Temperature"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"

  - platform: template
    name: "ESP Free Heap"
    unit_of_measurement: "kB"
    accuracy_decimals: 1
    update_interval: 30s
    lambda: |-
      return heap_caps_get_free_size(MALLOC_CAP_8BIT) / 1024.0;

